### ISSUE TITLE
Remove not linked and archive folders from live site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1028]
We'll keep them on the dev site, but removing them from the live site will help with search results not returning old documents.

**Comment by mcharg** [comment]
@cthomasONRR I removed all the archive and not linked folders and made sure we had all the files that were on Z on Y.  Not sure the best way to test this.

**Comment by cthomasONRR** [comment]
@mcharg I found the following archive and not linked folders:

- [ ] Z:\Laws_R_D\PubComm\PDFDocs\AA00\archive
- [ ] Z:\Laws_R_D\PubComm\PDFDocs\AA00\Not Linked
- [ ] Z:\Laws_R_D\PubComm\PDFDocs\AA01\archive
- [ ] Z:\reportpay\Handbooks\pdfdocs\Geopayor\Not Linked

I also wanted to list these "_vti_cnf" files because they appear to be archives:

- [ ] Z:\Laws_R_D\FRNotices\PDFDocs\_vti_cnf
- [ ] Z:\Laws_R_D\PubComm\PDFDocs\_vti_cnf

**Comment by mcharg** [comment]
@cthomasONRR Jerome said not to touch any of the vti_cnf files because they do something on the back end.
