### ISSUE TITLE
Bold GOV - Create powerpoint presentation and moderator questions 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1175]

**Comment by mcharg** [comment]
@lpgoldstein Here's the draft presentation.  I didn't update the numbers on the status slide, since I figure they'll keep changing until the day of the presentation.
https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/BOLD/BOLD_Presentation_ONRR.pptx?d=w90f206f3dafb46ffbd593272616327b7&csf=1&web=1&e=jY3pMe

**Comment by lpgoldstein** [comment]
@mcharg Here's the script - please take a look when you have chance https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/EXmS7W2nMwdCtMe2s5HC7-UBm_2KRcUMHkWMSfM3-j2aLw

**Comment by mcharg** [comment]
@lpgoldstein I took a look and added a couple comments.

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg I have drafted answers to the moderator questions, can you both please review and make any changes or additions. Thanks

**Comment by mcharg** [comment]
@lpgoldstein Do you have another doc with the script?  The one linked above says "old" in the file name and has questions from the one you copied.

**Comment by Maroyafaied** [comment]
https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/ERWPa1ycwH5IvStgzGoWBXIBEL3MjVH4ycKz_zrsSU0-Zg?email=Maroya.Faied%40onrr.gov&e=dzFsKA

**Comment by lpgoldstein** [comment]
@mcharg @Maroyafaied I went ahead and deleted the link to the old one.

**Comment by mcharg** [comment]
Reviewed and made a few edits.  Looks good.
