### ISSUE TITLE
Indian Service menu navigation is not the same order as the side navigation

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#129]
This issue was found in the content audit.

https://www.onrr.gov/IndianServices/index.htm

![image](https://user-images.githubusercontent.com/40175688/79778530-1428b800-82f6-11ea-9eb4-fde89793d26f.png)

**Comment by jennmalcolm** [comment]
@Maroyafaied changes are in dev. Please review.

**Comment by Maroyafaied** [comment]
There is "contact us" on the left that's not on the drop down. Otherwise looks good.
![image](https://user-images.githubusercontent.com/40175688/82597735-aa0a6980-9b66-11ea-98fc-14267e85b0d7.png)

**Comment by jennmalcolm** [comment]
In looking at that page more, I think maybe I should delete it from the left nav rather than adding it to the  main nav. It is only a page for FIMO, not for the other services like our outreach office or IESC, so I don't think it should just be on the nav and not clear whom the "Us" is. There is already a link at the top right of all of these pages to that same page. What do you think about just keeping that and removing it from the nav @Maroyafaied ? ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/0e9756e3-0c9b-403d-9ec6-cc0d6326e4aa)

**Comment by Maroyafaied** [comment]
@jennmalcolm yes I agree just deleted it from the left nav

**Comment by jennmalcolm** [comment]
changes live
