### ISSUE TITLE
Get rid of two-part navigation menus for about and Reporting/paying

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#147]
Should we put any of the content in the expanded parts under the main navigation? Check analytics for how much they are clicked on.

Related to #120

**Comment by jennmalcolm** [comment]
@mcharg please review changes in dev.

**Comment by mcharg** [comment]
Reporting/paying:
* Based on how little they're clicked, I would move the checklists to the bottom
* I don't think we need the "Resources" header (same goes for the headers on all the other menus)
* We should add a link to the main reporting/paying page (https://www.onrr.gov/ReportPay/index.htm) titled "Reporting/Paying Main" (same goes for the main pages on all the other menus)

About:
* I don't think we need the "Who we are" header"
* Overview already links to the main About page.  If we add "Section name" Main to the other menus, we should relabel this to match.
* The org chart is missing and that's the most clicked on item in the current menu (other than NRRD, but that's probably more likely clicked on on the homepage).  Maybe we could link it from the Leadership page rather than have a pdf linked in the menu.
* Do we link to the other pdfs (budget justification and highlights) from other pages?  These both got low clicks.  I'm not sure where budget justification belongs.  Maybe make it its own page?
* I would reorder the links by number of clicks:
  - About Main (add ONRR highlights here)
  - Leadership (add  link to the org chart)
  - Office Locations
  - Rules & Regulations
  - Employment Opportunities
  - Press Releases
  - Natural Resources Revenue Data
  - Committees & Coordination
  - FOIA
  - Presentations & Testimony
  - Anti-Harassment Program

**Comment by jennmalcolm** [comment]
Here are my questions/clarifications/responses about your comments @mcharg

1.So do you think we need the org chart in the navigation menu? I can do that, but isn't it kind of weird to have a link to a pdf in the main navigation menu? Right now in dev, it is available on the about overview page. 
2. I agree with you on the  headings. I'll remove them.
3. I will reorder the about and reporting/paying menus based on clicks and your suggestions. Are there others on valuation, compliance, and Indian services I should reorder? It's easier for me to make all change to the library once since I have to replace all of the pages with that library item on production.
4. The "main page" suggestion is a little complicated because not all of the menus have a what I would call a "main page." The index files for each are about/overview, compliance/overview, Indian Services/allottee assistance, and Valuation/valuation regulations. I think given this, and without creating new overview pages for valuation and Indian Services at this time, maybe we could just add a link for the main reporting/paying page and call it "overview" to be consistent with the other menus that do have an overview page. What do you think? We could also just call those three overviews (section name) Main if you think that clearer, but we will still have two menus without that.

**Comment by mcharg** [comment]
1. I think it's fine just on the about overview page.
3. Will add separate comments for recommended orders for the additional sections.
4. I'm good with your suggestion.

**Comment by mcharg** [comment]
Valuation
* Indian Gas Index Zone
* Indian Oil Major Portion
* NYMEX Oil Prices
* Unbundling
* Indian Gas Major Portion
* Valuation Regulations
* Federal Gas Index Option

Above is the order based on clicks, but it might still make sense to group like items regardless of clicks.

**Comment by mcharg** [comment]
Compliance can stay in the order it's in.  The only two links that got over 100 clicks are the first two.

**Comment by mcharg** [comment]
Indian Services can also stay in the order it's in.  They're in order of number of clicks.

**Comment by jennmalcolm** [comment]
Ok, I think I'll keep the Indian items as the first three by moving up Indian gas major portion. Otherwise, I'll go with what you suggested for valuation. Thanks.

**Comment by jennmalcolm** [comment]
I think I got all of these changes in dev. Could you give it one more once-over @mcharg?

**Comment by mcharg** [comment]
Looks good.

**Comment by jennmalcolm** [comment]
changes live
