### ISSUE TITLE
Content not appearing within tabs

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1582]
I'm working on Page ID 68: https://dev-onrr-cms.app.cloud.gov/admin/content/pages/68
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tab=overview

I was able to add the tabs without issue, and still see them fine on the dev site. I started adding content within the tabs without issue, and was seeing that content appear on the dev site. Now, on the dev site, none of the content within the tabs is appearing. I do not see any errors within the CMS that would prevent all content from showing.

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/da694fe4-16d6-414d-96e1-2bd6f2c73a31)

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/81109d01-2ecc-4298-bc0c-8bc8da249604)

**Comment by jlouis-onrr** [comment]
@cthomasONRR, you should be seeing the content get displayed now.  A couple of things were preventing this from appearing on the frontend.

1.  There is duplicate page with the same slug and url and the previous page was being rendered as it came across first in the url(page 67 - archived).  The fix for this was a permission adjustment so that archived pages are not readable from the api.

2.  The cms or database shouldnt allow for duplicate urls.  Im gonna create a issue to fix this bug with the url field.

**Comment by mcharg** [comment]
@jlouis-onrr That was one of the pages that mysteriously disappeared, so I created a new one.

**Comment by jlouis-onrr** [comment]
it was archived.  On the right hand panel there is a archive option that will allow you to see all pages regardless of their status.  The new issue that wont allow for duplicate slug creation should prevent this from happening again.

**Comment by cthomasONRR** [comment]
@jlouis-onrr I started adding new content, and I'm getting the same issue- Not all of the new content is appearing. I just added an expansion panel and it will not show up.
