### ISSUE TITLE
Menu on onrr.gov

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#166]
Something happened in the background code and the main menu bar across the top flips valuation and reporting/paying on everything but the home page.  Looks like you added "home" to the menu, so that may be when that happened.  Thanks!

**Comment by jennmalcolm** [comment]
Thanks @jpetersononrr. We actually are reorganizing all of the items in the navigation bars on all of the pages. We have them all updated in dev, but we are waiting until we're ready to push another change and add the anti-harassment page to push them all. The only reason some of them are changed on the live site already is because we have had to push other changes to those pages. We didn't expect to be waiting to long to push them all, but hopefully that will be possible next week. Thank you for submitting the issue though, and I will keep it open until we get the changes pushed to all of the pages.

**Comment by jennmalcolm** [comment]
All the menus should be the same, updated version now.
