### ISSUE TITLE
Reach out to Data Governance about the glossary

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1706]
And how it should interact with the meta definition project they're working on.

**Comment by cthomasONRR** [comment]
@mcharg Here is a draft of the meeting invite email I'm planning to send Wendy. Please review, then I'll look at the calendar and find a good time for everyone.

"Hi Wendy,

My name is Christine Thomas. I'm one of the program analysts in the Open Data, Design, and Development (ODDD) team. As you know, the ODDD team is working to redesign onrr.gov. Part of this redesign included adding terms to the ONRR glossary.

We completed work on the glossary, and would like to discuss how it should interact with the meta definition project your team is working on.

We would like to have a meeting to share with you the terms we included in our onrr.gov glossary. Please let me know if this day/time works for you!

Here are some additional information/background methodology about our glossary. We will go over this in the meeting, but I wanted to summarize it in this email as well. In order to identify relevant terms to add to the glossary, we targeted the 10 most frequently viewed webpages and pulled terms that needed defining from there. Most of these terms have already been defined in handbooks and other publicly available ONRR documents, but a few had not. Those terms that were not previously defined were sent to the appropriate SMEs for peer review. We then incorporated the SME peer reviews into the final definitions.

Thank you for your time,
Christine"

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
We met with Wendy Ranone. Data Governance is currently working on a "To-Be" glossary associated with BPR and also a "Lease & Agreements" glossary. They are currently in their pilot program for their new metadata management tool, which will house glossary terms.

She was happy that our onrr.gov glossary terms are already peer reviewed. I will email her my clean list of terms and also my spreadsheet that contains the peer review information. She will review and let us know if her team has any questions/concerns. I will set up a follow-up meeting for the first week of April.

In addition- she said that in the future, instead of contacting the GS-15s as SMEs to peer review, that we should go through the Data Stewards. These Data Stewards will appropriately peer review or delegate the peer review of new terms in the future.

**Comment by cthomasONRR** [comment]
I set up the next meeting for Tuesday  April 5 @1pm mtn.

@mcharg @Maroyafaied are yall good with closing this issue? We can make a new one for the next meeting in the appropriate sprint. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR Yes, you can close it.
