### ISSUE TITLE
Add Indian Index Zone instructions to CMS wiki 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1823]

**Comment by cthomasONRR** [comment]
@mcharg @lpgoldstein This section is ready for your review in the Wod document. I have it set in the navigation pane, since the document is so long now:

![image](https://user-images.githubusercontent.com/72526208/163038687-7e87b6b8-4851-4a41-b33e-d9e17944b290.png)


https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
@mcharg Great! This is in the wiki if you want to do a final review. https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide#Updating-pricing-collections

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
