### ISSUE TITLE
PDF "put" please :)

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#183]
I'm guessing you put all the pages sometime this weekend.  I had a page I was working on that thankfully was ready to go live, but the PDF that should be with it didn't get through nor did the images.  Could you "put" the images folder from Valuation and the "POP-example-Pre-2016-05212020-Final" in the pdf folder for Valuation?  Thank you!!  (Secretly also appreciate you just pushing the page ;))

**Comment by jennmalcolm** [comment]
Thanks @jpetersononrr I just pushed your requeted items to production. They should be live in 10 minutes or so. I did push all of the htm files this morning to get some changes to the navigation out there. I didn't notice that there was one you were working on, so I'm glad it wasn't a problem to get it out there. In the future, if you're working on a new page that you don't want to go live, could you mark the file name with something obvious (e.g., "WIP" for "work in progress" or "UNDER CONSTRUCTION") so that I don't mess up and accidentally push something that's not ready? Thanks.

**Comment by jpetersononrr** [comment]
Absolutely!  Thank you!!
