### ISSUE TITLE
Test contacts collection

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1949]

**Comment by Maroyafaied** [comment]
look into what happens to existing records when reuploading the same record.

**Comment by jlouis-onrr** [comment]
@Maroyafaied, @mcharg,  the upload functionality will append/and or add records to an existing record collection when the ID field is not used.  If the ID field is used and matching id matches the record it will be updated with the new values.

**Comment by Maroyafaied** [comment]
@jlouis-onrr Thanks for looking into it. @lpgoldstein @mcharg @cthomasONRR The ID field need to be selected from the download option. As  long as the id record along with columns being updated, the records will get updated with new values.  Otherwise if the Id is not used the records will get added to collection as new records.
