### ISSUE TITLE
Create better guidelines for submitting GitHub issues

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2104]
Improve this page: https://github.com/ONRR/onrr.gov-site/wiki/Using-github. Write better directions for ONRR members outside of the ODDD team, so that they can better understand how to clearly request changes to the website.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein 
I added more detailed instructions here: https://github.com/ONRR/onrr.gov-site/wiki/Using-GitHub#best-practices-for-writing-your-github-requests

Could one of you review and let me know if you can think of anything else that should be added. Thanks

**Comment by Maroyafaied** [comment]
@cthomasONRR this is great and will be very helpful as resource. Here are my recommendations;

1. Refer to our accessibility policy in the last bullet point: https://github.com/ONRR/onrr.gov-site/wiki/Accessibility-Policy
![image](https://user-images.githubusercontent.com/40175688/184694362-a91c554f-dd8c-4982-8bc8-558f37953eab.png)

2. Let's add a sentence to this intro saying " We will work on your request as soon as possible but we ask that you allow 24 hours for your request to be completed to account for other work priorities and staffing resources on our team. " or anything along the same lines. 
![image](https://user-images.githubusercontent.com/40175688/184695011-91f32547-9a0d-4885-ab10-8895b8143f28.png)

3.  Since we generally prefer that they keep the file name the same when replacing/updating documents, should we re-word this bullet point? or say "if the updated file name is different than the current file on the website, please specify by giving clear instructions such as "Please replace [oldfilename] with [newfilename]".
![image](https://user-images.githubusercontent.com/40175688/184695211-09dcf41a-10ce-47e5-a433-c4ee16dabf25.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, these are really good suggestions! I updated the page accordingly: https://github.com/ONRR/onrr.gov-site/wiki/Using-GitHub#best-practices-for-writing-your-github-requests. If you're good with this, I'll send it to Jessica.

**Comment by Maroyafaied** [comment]
@cthomasONRR Looks great! Yes go ahead and send it to Jessica. Let's let @lpgoldstein review before closing the issue incase there's something specific she'd like to mention.

**Comment by lpgoldstein** [comment]
@cthomasONRR This looks great. Thank you!
