### ISSUE TITLE
Re-add files without a pptx or word icon 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2178]

**Comment by cthomasONRR** [comment]
@Maroyafaied I added a bunch of icons across the site, most were associated with training or docs that get updated frequently. It's on the beta site now if you want to do a quick spot-check. Thanks!

**Comment by Maroyafaied** [comment]
- Needs ppt icon 
![image](https://user-images.githubusercontent.com/40175688/190494276-def3b0b2-ce43-446e-a8b2-5dc9b28c29a7.png)

- This one doesn't have a link at all  https://beta.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-agreements
![image](https://user-images.githubusercontent.com/40175688/190496544-6db938ce-4c25-4c9c-a761-b9e6e072ff8d.png)

-not sure if this one is supposed to be a file or if it's really supposed to go to the tab that it does. https://beta.onrr.gov/references/reference-lists?tabs=revenue-reporting-references
![image](https://user-images.githubusercontent.com/40175688/190496282-52119da2-5deb-420e-94d9-30bd3e6179b9.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied 

The first one- there is only 3 bullet points... the PDF link title is "Solid Mineral Compliance Processes" so it's correct: 
![image](https://user-images.githubusercontent.com/72526208/190500095-b7ba11ae-a620-40bd-92a3-c96fba6dcc05.png)

The second one- the "Sorted by State and Agreement Name" doc was removed from both sites. I forgot to also delete the text here. It's now removed in dev:
![image](https://user-images.githubusercontent.com/72526208/190500758-de8450c6-4215-4251-b322-5f11123a47c1.png)

The third one- yes it's supposed to route to /references/reference-lists, so that's correct.

**Comment by cthomasONRR** [comment]
@Maroyafaied 
This update is in beta:
![image](https://user-images.githubusercontent.com/72526208/190692130-70ce604b-e922-4c88-9fa6-a3d3317a88e9.png)

Closing this issue.
