### ISSUE TITLE
Create presentation for GSA's Fedpreneur Show & Tell

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2223]
Combine existing onrr.gov Plain Language and 4-Point Hybrid Testing presentations into one.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein 

A PPT that combines the Plain Language and 4-Point Hybrid Testing presentations can be found here:
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/GSA_Fed%20Show%20and%20Tell_November22.pptx?d=w3e0e7527a7754a98959005e65f3356bf&csf=1&web=1&e=AHvS4X

Please review and let me know if I should change anything.

Thanks!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR This presentation is ready for your review.

**Comment by eelzi-ONRR** [comment]
Overall it's great! I found it easy to follow and no errors or typos. So consider my feedback as minor suggestions - the presentation would be fine as is.

Slide 4 - change "two weeks to a month" to "2-4 weeks"
Slide 7 - inconsistent spacing between bullet points (but that might be intentional for this and the other slides where I list it?)
Slide 20 - no need for a single bullet
Slide 22 - inconsistent spacing between bullet points 
Slide 30 - reword "in every step outlined above" because there is nothing above this on the slide
Slide 31 - remove "for us" from the last bullet - because it should be an ongoing process for everyone as we learn more about the needs of users with disabilities, not just us :)
Slide 32 - bullets 2 & 4 are redundant
Slide 38 - change "Once we got the dev site built" to "Once we built the dev site" to be less passive voice
Slide 27 - inconsistent spacing between bullet points 
Slide 32 - inconsistent spacing between bullet points

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

Thanks for your review! I addressed your comments in the PPT and below.

- [ ] Slide 4 - change "two weeks to a month" to "2-4 weeks" **Fixed**
- [ ] Slide 7 - inconsistent spacing between bullet points (but that might be intentional for this and the other slides where I list it?) **This is intentional- separating the prototype link from the blog links**
- [ ] Slide 20 - no need for a single bullet **Removed the bullets**
- [ ] Slide 22 - inconsistent spacing between bullet points **This is intentional- separate lists**
- [ ] Slide 30 - reword "in every step outlined above" because there is nothing above this on the slide **Reworded to "In every step outlined in the previous slides"**
- [ ] Slide 31 - remove "for us" from the last bullet - because it should be an ongoing process for everyone as we learn more about the needs of users with disabilities, not just us :) **Fixed**
- [ ] Slide 32 - bullets 2 & 4 are redundant **I'm keeping. Somewhat redundant, but 2nd bullet is acknowledging specifically to onrr.gov; 4th bullet is task for all of our websites**
- [ ] Slide 38 - change "Once we got the dev site built" to "Once we built the dev site" to be less passive voice **Fixed**
- [ ] Slide 27 - inconsistent spacing between bullet points **This is intentional- separate lists**
- [ ] Slide 32 - inconsistent spacing between bullet points **This is intentional- trying to separate out thoughts**

**Comment by Maroyafaied** [comment]
@cthomasONRR The presentation looks good. Just a couple of thoughts, someone asked at the IAAF conference if the website meets the WCAG requirements, this[ link is a quick reference ](https://www.w3.org/WAI/WCAG21/quickref/)to the requirements. It might be good to include the link somewhere in the presentation or to mention the four main requirements ( Perceivable, Operable, Understandable, Robust).  Another thought is, it might be a good visual to have a screenshot of lighthouse audit accessibility score on the current website and compared with a screenshot of  the lighthouse audit accessibility scores for the beta site (not sure if lighthouse gives an overall score). Just thoughts, otherwise looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied I added Slide 20 to address WCAG and just the general fact that we incorporated accessibility requirements from the start of the redesign: 

![image](https://user-images.githubusercontent.com/72526208/197209600-6e0a8068-56a5-4d5f-aeb1-1241fe111ce2.png)

**Comment by cthomasONRR** [comment]
Lindsay reviewed via chat.
