### ISSUE TITLE
Build new Indian interactive example "IPMP"

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2252]
**Indian Example: Initial Reporting for Processed Gas in Non-Index Zone (Major Portion) Areas**

https://beta.onrr.gov/document/Initial.Reporting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

I think I'm finished with my example... want to review? I had to hand-type all the info/caution cards because the PDF wouldn't let me copy+paste that info... so if you could looks at those closely for typos I'd really appreciate it! Thanks!
https://dev-onrr-frontend.app.cloud.gov/references/valuation/ipmp

**Comment by eelzi-ONRR** [comment]
@cthomasONRR  It mostly looks good! Just a few minor formatting/style edits to make, and a couple inconsistencies between this one and the existing interactive examples.

**Overview tab** 

- Hyperlink in the Contact box goes to onrr.gov instead of a mailto (this is a problem with the box we're reusing - it needs to be updated there)
- In the first section, change "possible" to "possibly" and add a comma after "three"

**Detailed Example Tab**
- Assumption 7:  I totally understand why you used the bold (A.) and (B.) since we can't have indented lists, but that's the format used throughout to refer to parts on the sample statement, so these look a little confusing. Maybe if we use a.) and b.) - that might be more obvious that these letters don't refer to the statement?
- Assumption 7: "downstream" and "less" should be bold

- Transportation Allowance Alert: remove the period at the end of the hyperlink (as per our CMS styleguide)

- Transportation Allowance Step 2: suggest making the italics bold instead. More than 2-3 consecutive words in italic is hard to read online

**Differences between this one and the existing interactive examples** (let me know what you choose as the way to do these - I may need to make some changes to the one I'm working on depending on what you decide)

- The statement you have in the intro block exists is on the Overview tab for other examples
- Assumptions expanding list is labeled differently that the existing examples (this one includes the full name of the example, the others just say Assumptions)
- In the 2016 example, Product Code is spelled out in the heading for each tab. This one uses PC in the heading.
- Sample statement - the word BOLD is in all caps for this one, it's lowercase in other interactive examples

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

Thanks, here is what I did:

**Overview tab** 

- Fixed the hyperlink to have the "mailto", should be fixed everywhere (update in dev not yet in beta)
- Changed "possible" to "possibly" and added a comma after "three"

**Detailed Example Tab**
- Assumption 7:  Changed to use a.) and b.)... hopefully when we get more bullet options I can revise 
- Assumption 7: Bolded "downstream" and "less" 

- Transportation Allowance Step 2: Removed italics and bolded

**Differences between this one and the existing interactive examples** (let me know what you choose as the way to do these - I may need to make some changes to the one I'm working on depending on what you decide)

- I moved this intro statement to the overview tab... RV might want us to add something above those first-level tabs, but we'll see what they say
- I included the full name of the example in the Assumptions panel header, because I was having trouble with there being multiple existing "Assumptions" panel headers, and getting the correct one so that the panel defaults to open. I don't think this is a big deal, but I think going forward I'm going to have the full example name to avoid confusion in the CMS.
- I spelled out Product Code in the headings for each tab. 
- Sample statement - I think "BOLD" is in all caps makes more sense, because the letters are upper case in the statement. I went back an updated the 2016 example (update in dev, not beta)

**Comment by eelzi-ONRR** [comment]
I did a quick review of the changes you made - the contacts now has https:// in the mailto, so that needs to be removed.

Everything else looks great!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks! I'm going to close this issue now and I'll open new issues for any RV requested revisions. Hoping we can send these to RV next week!
