### ISSUE TITLE
Federal Benefits Open Season - Discussion!

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2264]
Let's post health insurance/vision/dental/etc plans we're happy with here. 
Also please feel free to post questions so others can answer!

**Comment by lpgoldstein** [comment]
I'm going to go with this plan https://www.uhcfeds.com/health-plans/plan-details.hdhp.80210.selfOnly.biweekly
There's a premium pass through of $1500 which takes the deductible down to $2500, and the premium payment for my whole family is around $400 a month. We figured out last year that the money we would save on premiums even including the deductible - saves us around $1500. We will max out our HSA - which never expires and you can invest - but we will probably use it all because I use a lot of non-covered services. It includes preventative dental for kids and an annual eye exam. I will only get dental insurance for my husband and I. If a kid has a cavity - I will directly negotiate the price and it will be cheaper than paying a larger premium. Then I will also max out my dental vision fsa for my dental work.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein The United HDHP is what I have now - I can't speak much to it yet except that I chose it because it covers all my existing doctors, no referrals needed for most specialists, a flat rate instead of percentage for most appointments and services. One drawback is that physical therapy sessions are limited to 20 per year.

When I was comparing, I considered what I paid out of pocket for knee surgery last year and all the follow-up appointments as an example, and found the same thing you did - that the higher deductible plan worked out in my favor versus paying a higher premium.

I should have a specialist claim and a custom ortho brace go through in the next couple weeks, so if I have any more feedback based on those, I'll let you know!

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Thank you! I have that same plan but through my husband's work and the coverage isn't as comprehensive as the federal plan. I just need to stop seeing people that are out of network.
