### ISSUE TITLE
Figure out CMS updating - adding new plugin 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2313]

**Comment by greensomes** [comment]
Done. The README inside the editorjs directory outlines the process for building the extension when anything is changed, including the addition of a new plugin. The process is to execute `nom run dist` from editorjs. Once complete, commit the change to cms/extensions/interfaces/editorjs/index.js and push to GitHub.

The circleci pipeline to deploy changes to the CMS must be triggered manually since changes are not made frequently. To do this, manually trigger a pipeline from the desired branch and add a boolean parameter with the key "run_cms_updates" and value "true". The "update-cms" job will then run to deploy changes to the CMS application in cloud.gov,
