### ISSUE TITLE
Move sort by arrow in line with column header on reporter letters page

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2396]
Move the sort by arrow to be to the right of "Date" instead of above it. Also try to make the arrow display all the time.

https://onrr.gov/references/reporter-letters 

How we want it to look and what might work for the code:
![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/7628cfcf-7f21-4766-867b-4e00f6ec990f)

Maroya will show me where the code file is to make this change.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR this is ready for your review, the easiest way to fix it was to use <span> instead of <div>, the file to change the code can be found here , I made the change in line 53. I think making the sort arrow appear without having to hover is a bit more complicated so we can make another issue for that for a developer. 
https://github.com/ONRR/onrr.gov-site/blob/dev/frontend/src/components/collections/ReporterLetters.vue

**Comment by eelzi-ONRR** [comment]
This looks good! 

We can do a quick user research gathering on the arrows in the near future. It might not be as confusing as we think it is
