### ISSUE TITLE
Meet with Search.gov about accessibility with onrr.gov's search

### ISSUE THREAD

**Issue by AlexandracmONRR** [ONRR/onrr.gov-site#2442]

**Comment by AlexandracmONRR** [comment]
Hi Team - Below I've linked the questions for the Search.gov meeting on Monday (2/6). Could you review the questions and make any edits, comments, additions related to the search engine?

Also, I've checked ZenHub and did not see any backlog issues related to the search engine, but if you think of anything, please go ahead and add it!

https://doimspp.sharepoint.com/:w:/s/NRRD/ETkduLAu_VdLmW6ljKpF2bYBv6QsKed-Udv1l_Vs9qTU-g?e=ZZUBrQ

Thank you,
Alex

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I reviewed, and it looks great! This will definitely help facilitate a good conversation with search.gov. Based on previous meetings, they are all very friendly and willing to help!

**Comment by cthomasONRR** [comment]
I took some screen grabs of the wireframes:

Faceted search filters (left site) - desktop view:
![image](https://user-images.githubusercontent.com/72526208/217070749-4b117f5a-ceef-45f9-84e2-a5e2018cdc8f.png)

No search filters- tablet view:
![image](https://user-images.githubusercontent.com/72526208/217070904-39fb42e0-67c1-4cfe-b936-3b26dde473f4.png)

New footer components:
![image](https://user-images.githubusercontent.com/72526208/217070933-41657ac9-cd04-44d1-a821-c0d9ffbdb22e.png)


I'll work on getting 5 representative NRRD urls, and will post them here too.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Here are some representative types of webpages on NRRD:

- Homepage: https://revenuedata.doi.gov/
- Main download data page: https://revenuedata.doi.gov/downloads
- Download data page unique to data type: https://revenuedata.doi.gov/downloads/production-by-month/
- How Revenue Works: https://revenuedata.doi.gov/how-revenue-works
- Native American Governance (consistently most-viewed page): https://revenuedata.doi.gov/how-revenue-works/native-american-ownership-governance/

@lpgoldstein Not sure if we want to include Query Data and Explore Data? I don't expect these pages to be indexed and searchable since there are almost 100% dynamic content.

- Query Data: https://revenuedata.doi.gov/query-data
- Explore Data: https://revenuedata.doi.gov/explore?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022

**Comment by AlexandracmONRR** [comment]
Hi all, I've inserted the notes from today's call into the same document that held the questions. Please see link below and add/edit as needed:
https://doimspp.sharepoint.com/:w:/s/NRRD/ETkduLAu_VdLmW6ljKpF2bYBv6QsKed-Udv1l_Vs9qTU-g?e=ZZUBrQ

**Comment by AlexandracmONRR** [comment]
Response from Amani (amani.farooque@gsa.gov) on 2/8/2023: 

**Q: Thanks for unblocking the "www" URLs. We have checked and they seem to be appearing in our results again. Based on the results we are getting, we have a couple more questions. Is it possible to adjust our indexing? Specifically, is there a way that we can index the 2nd level tabs? For example, a search for NYMEX doesn't bring up the specific tag. We previously tried adding these links to our XML sitemap, but the sitemap wouldn't validate because if the ? in the link.**

- A: We only support page-level indexing, so the tabs represented by query parameters (?tabs=pricing,nymex-oil-prices) would not be indexable even with those links explicitly added to the sitemap. 
 
**Q: Do you have an API that will allow us to push updates for indexing for specific content types? Since our sitemap doesn't update the last mod date automatically, we're wondering what options you might have for pushing reindexing sooner than once a month.**

- A: We also do not have an API to trigger re-indexing, but we are scoping out ways to better expose indexing management within our Admin Center within the next year or two. In the meantime, you should definitely feel free to reach out to us at search@gsa.gov to request a reindex - happy to support as often as you need!
