### ISSUE TITLE
Create page for new ONRR 2020 Valuation Reform and Civil Penalty Rule

### ISSUE THREAD

**Issue by templind** [ONRR/onrr.gov-site#245]
Attached is the PDF rule for - ONRR 2020 Valuation Reform and Civil Penalty Rule

Please make updates to the following web pages as follows:

Access:

https://www.onrr.gov/Laws_R_D/index.htm

Under heading "Rules" and drop-down sub-heading "ONRR Rulemakings", above the last posting - add "AA27:
ONRR 2020 Valuation Reform and Civil Penalty Rule" - Hyperlink with attachment.  
Then, the hyperlinked "AA27:  ONRR 2020 Valuation Reform and Civil Penalty Rule" should lead to a new page with the following content:  

 (please use the existing link https://www.onrr.gov/Laws_R_D/2020ProposedValRule.pdf for the attachment and follow the same format as the web page for "AA24: Inflation Adjustments to Civil Monetary Penalty Rates for Calendar Year 2019" under https://www.onrr.gov/Laws_R_D/FRNotices/AA24.htm)

Regulation Identifier Number 1012-AA27
ONRR 2020 Valuation Reform and Civil Penalty Rule
30 CFR Parts 1206 and 1241
[ONRR Proposed 2020 Valuation Reform and Civil Penalty Rule.pdf](https://github.com/ONRR/onrr.gov-site/files/5035899/ONRR.Proposed.2020.Valuation.Reform.and.Civil.Penalty.Rule.pdf)

Abstract: The Office of Natural Resources Revenue is publishing this proposed rule to amend portions of its regulations for (1) valuing oil and gas produced from Federal leases for royalty purposes, (2) valuing coal produced from Federal and Indian leases, and (3) assessing civil penalties for violations of certain statutes, regulations, leases, and orders associated with mineral leases. 

Proposed Rulemaking: [Hyperlink "Proposed Rulemaking" with attached PDF] (08/06/2020)

**Comment by jennmalcolm** [comment]
@templind and @mentastc everything should be ready in our dev site. Please review. Let me know if you see anything you want changed.

Otherwise, please let me know when you want to release these changes to the live site.  

http://2017onrr/Laws_R_D/index.htm

**Comment by mentastc** [comment]
Hi Jennifer,

Looks good to me, I just have one comment for Dane. Should the heading have the word proposed in it?

Thanks,


Chris Mentasti | Communications Manager

Office of Natural Resources Revenue | U.S. Department of the Interior

(202) 809-5513

Chris.mentasti@onrr.gov<mailto:Chris.mentasti@onrr.gov>

________________________________

**Comment by mentastc** [comment]
I think that is okay for now because all we have is a proposed rule.  We would revise the heading, abstract, etc. to update the page for a final rule.  For example, the 2016 Valuation Rule's page contains the publications leading up to the final rule - http://2017onrr/Laws_R_D/FRNotices/AA13.htm


Dane Templin
Regulations Supervisor
Office of Natural Resources Revenue
Office: 303-231-3149 Cell:  303-396-9070
Bldg. 85, Denver Federal Center MS 62150B

P.O. Box 25165 Denver, CO 80225

Warning: This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by mentastc** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
