### ISSUE TITLE
Fax number listed twice on FIMO contacts page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#462]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6760e850-bfa4-4105-86d9-406387036147)

**Comment by mcharg** [comment]
And another one:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d050e7a1-305f-4ba4-b994-953b0fdacf6f)

**Comment by jennmalcolm** [comment]
Please review in dev @mcharg. The two fax numbers for Window Rock were different, so I went with what I found here:

https://www.bia.gov/sites/bia.gov/files/assets/bia/navreg/Agency%20Office%20info.pdf

Also, I don't think we should have pagination with this list because the second page is so short, and I didn't even notice it at first. What do you think about removing that?

**Comment by mcharg** [comment]
@jennmalcolm Updates look good and I think it makes sense to remove the pagination.

**Comment by jennmalcolm** [comment]
changes--including no more pagination--live
