### ISSUE TITLE
Rewrite Indian content to reduce reading level

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#542]

**Comment by mcharg** [comment]
@Maroyafaied 
Tribal consultation: https://qmcq5k.axshare.com/#id=htd1ha&p=tribal_consultation

**Comment by mcharg** [comment]
@Maroyafaied 
Indian references: https://qmcq5k.axshare.com/#id=xj5291&p=indian_references

**Comment by Maroyafaied** [comment]
@mcharg here is my changes for section home, it's grade level 10 on Hemingway, I'll work on the others as I get breaks from my training.  
"The Office of Natural Resources Revenue (ONRR) has a trust responsibility to Indians. The Federal Indian Minerals Office (FIMO)  ensures the trust responsibility is met and sorts out Indian mineral issues. The Indian Outreach program serves as a focal point for the Indian community. They sort out Indian mineral issue and are the primary contact for the Indian community, Indian mineral owners, and involved state and federal agencies.  "

**Comment by mcharg** [comment]
@Maroyafaied Last one.  There's not much copy on this one.

Indian Payments: https://qmcq5k.axshare.com/#id=khr15i&p=indian_payments

**Comment by Maroyafaied** [comment]
@mcharg my changes for the FIMO page, it's at grade level 9. 

 Federal Indian Minerals Office (FIMO) 

Background
 
The Federal Indian Minerals Office (FIMO) provides Indian Trust services to individual Indian beneficiaries in the management of their oil and gas mineral resources. Indian allotted oil and gas management functions are under one line of authority. 

The Bureau of Indian Affairs (BIA) and the Office of Natural Resources Revenue (ONRR), work with the  Bureau of Land Management (BLM) and the  Office of Special Trustee for American Indians (OST) to provide full customer service for Indian allotted mineral interest. The first office of its type is in Farmington, New Mexico. FIMO-Farmington provides services for individual Navajo mineral owners in the Four Corners Region. Being located in Farmington gives personnel an understanding of local market conditions. This ensures familiarity with minerals sales and royalties distributions to Navajo mineral owners. 

Inspection and Enforcement FIMO works with BLM and other agencies to:

· inspect all Navajo allotted oil and gas leased lands.

 
 

· enforce mining regulations about operational, surface, and environmental issues.

 
 

· approve applications for permits to drill.

 
 

· approve gathering systems, alternate measurement methods, Right of Way designs, and abandonments.

 
 

· conduct physical inspections of oil and gas sale facilities.

 
 

· investigate oil theft and other undesirable events.

 
 

Lease Administration FIMO manages Navajo allotted leases. Management activities include: 

 
 

· processing ownership changes.

 
 

· obtaining proper bonding.

 
 

· collecting bonuses.

 
 

· overseeing lease sales.

 
 

· assessing values.

 
 

· monitoring rentals.

 
 

· canceling leases.

 
 

Note: Lease sales are currently on hold. 

Royalty Compliance 

FIMO also conducts compliance activities for Navajo mineral owners.  These include: 

 
 

· accounting for mineral royalties.

 
 

· reviewing volumes used to compute royalties on Indian leases.

 
 

· ensuring methods used to compute royalties follow federal laws, regulations, and lease terms.

 
 

Support for Other Indian Mineral Owners FIMO supports other Indian Mineral Owners and tribes upon request and as appropriate.

**Comment by mcharg** [comment]
@Maroyafaied Can you take a look at the IESC page overview tab?  It's grade 13. I think it's the only one that's still above grade 10.

**Comment by Maroyafaied** [comment]
@mcharg this should be grade 10. 

About 

The Indian Energy Service Center (IESC) is a collaboration between four agencies. The agencies representing the IESC are; Bureau of Indian Affairs (BIA), Bureau of Land Management (BLM), Office of Natural Resources Revenue (ONRR), and Bureau of Trust Fund Administration (BTFA). 

Mission 

Streamline business processes to efficiently develop the Indian mineral estate while protecting trust assets by removing barriers to energy and mineral development on Indian lands. 

History

The Indian Energy and Minerals Steering Committee (IEMSC) recommended the creation of the IESC. The purpose of the IESC is to address the growing backlog at agencies due to the increased activity in various parts of Indian country. Approved by the Assistant Secretary of Indian Affairs, the IESC received federal funding in FY 2016 and begin hiring staff from BIA, BLM, and ONRR. .

The Service Center Director reports to the BIA Deputy Bureau Director – Trust Services of BIA. Each agency has an onsite branch chief who oversees the duties of the employees from their agency. The four branches of the IESC are: 

· Real Estate Services (BIA), 

· Engineering Services (BLM), 

· Mineral Services (ONRR) and 

· Beneficiary Services (BTFA). 

Principles

Each of the four principles was a collaboration of principles from each of the four agencies represented at the IESC.

 
 Quality of Life

BIA’s mission is to enhance quality of life, promote economic opportunity, and to protect and improve the trust assets.

Stewardship
 
BLM is the steward of all public and trust lands.

 Accountability

ONRR collects, accounts for, and verifies natural resource and energy revenues due.

Beneficiary Focus 

BTFA focuses on protecting, preserving, providing for, and engaging with beneficiaries and all Indian trust assets.

Main Functions

 The main functions of the IESC are to:

· provide a cost effective, centralized, and multifunctional processing capacity. 

· standardize and streamline business processes across Interior’s Indian energy organizations.
 
· streamline processes in the recently developed Onshore Federal and Indian Energy and Mineral Lease Management Standard Operating Procedures (SOP). This is a business process that simplifies processing activities while assuring fulfillment of Interior responsibilities in Titles 25, 30, and 43 of the Code of Federal Regulations.

· train DOI employees in SOPs to support streamlining and standardizing process.

· create new guidance for Tribal Energy Resource Agreement (TERA) and Tribal Energy Development Organization (TEDO) processing. This guidance is pursuant to Interior Secretarial Order number 3377 and will be included in the Onshore Energy and Mineral Lease Management Interagency SOP. It will discuss the policies and procedures of TERA/TEDO applications as well as roles and responsibilities of DOI offices. The IESC will administer Title I Self-Determination contracts for oil and gas activities on trust lands with the BIA, BLM and ONRR.
