### ISSUE TITLE
WebCenter Portal User Guide

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#591]
Hello, please replace the "Data Warehouse training" Power Point with the attached "WebCenter Portal User Guide"
At the following location -
https://www.onrr.gov/reportpay/training/TrainingFiles/Houston%20Reporter%20Training/DataWarehouse.pdf

Thank you

[Industry WebCenter Portal User Guide_03_02_2021.pptx](https://github.com/ONRR/onrr.gov-site/files/6192865/Industry.WebCenter.Portal.User.Guide_03_02_2021.pptx)
 Power Point.

**Comment by mcharg** [comment]
@Maroyafaied See #593.  This is on a page that @bowlenj said can be removed.

**Comment by merrellc** [comment]
Please add at the below link under Training Presentations -

https://www.onrr.gov/ReportPay/training/index.htm
Training - Office of Natural Resources Revenue<https://www.onrr.gov/ReportPay/training/index.htm>
Executive Order 13891, "Promoting the Rule of Law Through Improved Agency Guidance Documents" directs all Federal agencies to ensure their guidance documents clarify only existing obligations that significantly affect the public, and do not create binding requirements outside of those developed through activities regulated by the Administrative Procedure Act.
www.onrr.gov


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: mcharg ***@***.***>
Sent: Wednesday, March 24, 2021 11:45 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebCenter Portal User Guide (#591)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Maroyafaied<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaroyafaied&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C171a20cad06d476cac7808d8eeecaec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637522047603306482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FAIYWCxqxJF8wfOMCuU1hjbJZdRjgNriiu9I8Ans85c%3D&reserved=0> See #593<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F593&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C171a20cad06d476cac7808d8eeecaec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637522047603316438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SIwCf4Naz6jhKAslARdmYdk7hK4MWXc4OLC%2Fl27FJt8%3D&reserved=0>. This is on a page that @bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C171a20cad06d476cac7808d8eeecaec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637522047603316438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KiSH%2F8hHfthSz%2Fisko9miWyHk%2Fu22ahj%2FUBqigrPttU%3D&reserved=0> said can be removed.

**Comment by mcharg** [comment]
We would like to have the WebCenter Portal User Guide’s source location be  with the ONRR WebCenter (eCommerce) Portal link at - https://www.onrr.gov/reportpay/index.htm:

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/36af0e0a-4871-49d6-9c98-dbed9a7d3202) 



 

Please also add the presentation to the list under Training Presentations - https://www.onrr.gov/reportpay/training/index.htm
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e2e5694d-94d5-44ae-96b3-9a4dde60d1bc)


 

Can we then add the User Guide source location link to the below locations:

Production Reporting page

Royalty Reporting page

Solid Minerals Reporting page

**Comment by mcharg** [comment]
@Maroyafaied I'll take this issue, since it's related to the training page issues in #593. I'll do both next week.

**Comment by bowlenj** [comment]
Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Thursday, March 25, 2021 9:04 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebCenter Portal User Guide (#591)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Maroyafaied<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaroyafaied&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C626f0cc0d50d453761b508d8ef9f4c50%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637522814755405434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KL6sIK0Q7z7u8m3fkotmUGhNbpaTj%2FpLlqCRIS36%2BA8%3D&reserved=0> I'll take this issue, since it's related to the training page issues in #593<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F593&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C626f0cc0d50d453761b508d8ef9f4c50%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637522814755415400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xsBPhVpcz16wGZF3BJ5nSPJqrE%2FWpf37KUPmQKja89E%3D&reserved=0>. I'll do both next week.

-

**Comment by mcharg** [comment]
@bowlenj @merrellc I added the link to the WebCenter portal user guide to the Overview page and the reporting right nav on the other reporting pages in dev.  Let me know if it's good to post to the live site. I also updated the copy under WebCenter Portal on the overview to be what we're changing it to with the redesign that's more industry centered.  http://2017onrr/reportpay/index.htm

I'll make the changes to the training page as part of #593 that I'll get to later today.

**Comment by merrellc** [comment]
Thank you. Looks good.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: mcharg ***@***.***>
Sent: Monday, March 29, 2021 9:50 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebCenter Portal User Guide (#591)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C19a34cf9164a465aa1a308d8f2ca7f49%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637526298826668596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=370Klaz3IUpngZHWcZ01zHOlEDWJR01eHGVd5yY2rd8%3D&reserved=0> @merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C19a34cf9164a465aa1a308d8f2ca7f49%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637526298826668596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mwETZZTaWBsO49yiBbbo82Tzy3HGTRNxwXkuh%2FRCwb0%3D&reserved=0> I added the link to the WebCenter portal user guide to the Overview page and the reporting right nav on the other reporting pages in dev. Let me know if it's good to post to the live site. I also updated the copy under WebCenter Portal on the overview to be what we're changing it to with the redesign that's more industry centered. http://2017onrr/reportpay/index.htm

I'll make the changes to the training page as part of #593<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F593&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C19a34cf9164a465aa1a308d8f2ca7f49%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637526298826678550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=61x%2FefCAn9XQaUxZdEakWZ3UWaobNMJJnPCPu2WEYQk%3D&reserved=0> that I'll get to later today.

**Comment by mcharg** [comment]
@merrellc I pushed these changes to the live site.  It might be a bit before they show up.
