### ISSUE TITLE
Apply Enforcement feedback to wireframes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#640]

**Comment by mcharg** [comment]
@Maroyafaied Do you have any feedback on this before I send it to the enforcement team?
https://qmcq5k.axshare.com/#id=5w0f4w&p=enforcement

**Comment by Maroyafaied** [comment]
@mcharg this is minor but  it says $60 on the current site.  Also, should we include these two bullet point under Litigation support?  In the last pic, it sounded like form Michael's email that he wanted that tab to be called "Overview" instead of "Enforcement" ?Everything else looks good.
![image](https://user-images.githubusercontent.com/40175688/114760458-8e7af500-9d1c-11eb-8c0c-45dca20e2f02.png)
![image](https://user-images.githubusercontent.com/40175688/114761739-23322280-9d1e-11eb-8f75-a18c414c764b.png)
![image](https://user-images.githubusercontent.com/40175688/114762167-ad7a8680-9d1e-11eb-8523-a6cdc8d9218a.png)

**Comment by mcharg** [comment]
@Maroyafaied I made the change to the civil penalty amount.  The two bullets for litigation support duplicated content that's in the bankruptcies section.  The tab was Overview, but when Michael said he wanted litigation support content on its own tab, it made more sense to change it to Enforcement, since it has only Enforcement content now.
