### ISSUE TITLE
Indian Index Zone county lists not working

### ISSUE THREAD

**Issue by sudarr** [ONRR/onrr.gov-site#72]
https://www.onrr.gov/Valuation/allzones.htm

The county list pop-ups for the three OK zones aren't working.

Also, we can remove the whole "Updated Zone Prices" frame on the right because those are now a year old and the pop-up isn't working anyway.

**Comment by jennmalcolm** [comment]
Hi @sudarr we had another issue with some depricated third-party code that may have caused the county pop-up issues as well because we fixed that, and the county pop-ups seem to be working fine now. I've also removed the "Updated Zone Prices" in the dev site, so please review to let me know if this looks ok to you.  Thanks.

http://2017onrr/Valuation/allzones.htm

**Comment by sudarr** [comment]
It looks great on the dev site and the pop ups work perfectly. Thanks

**Comment by jennmalcolm** [comment]
updates are live
