### ISSUE TITLE
Create "How to Update Pages in CMS" guide for ONRR.gov wiki

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#867]

**Comment by cthomasONRR** [comment]
@jkwonatx I added a folder for all wiki guides for CMS:
![image](https://user-images.githubusercontent.com/72526208/160450586-1c2b72b9-cf10-48fd-80f8-618445189103.png)


https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Wiki%2520Guides&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FCMS%252FWiki%2520Guides

**Comment by cthomasONRR** [comment]
@Maroyafaied @jkwonatx Maybe we should divide up the CMS instructions by topic. Here's some topics where I can write instructions:

- [ ] Building a new webpage
- [ ] Setting up tabs and accordions within a webpage
- [ ] Setting up cards and page dimensions
- [ ] Adding images and proper tagging
- [ ] Adjusting images
- [ ] Creating tables
- [ ] Adding external links
- [ ] Adding internal links
- [ ] Adding documents (PDFs, Microsoft docs) and proper tagging
- [ ] Linking to PDFs and other documents

**Comment by jkwonatx** [comment]
I'm happy to follow the direction/format you set @cthomasONRR @Maroyafaied

**Comment by cthomasONRR** [comment]
@jkwonatx @Maroyafaied I'm in training until noon, but after that I can set up a shared document where we can draft what should go in the wiki. If you and Maroya are good with those categories I listed, I can set up the word document that way. Then we can create a GitHub issue per category, and also divide up the categories so we don't step on each other's toes.

**Comment by Maroyafaied** [comment]
@jkwonatx forgot the screenshot, here it is. 
![image](https://user-images.githubusercontent.com/40175688/160674895-a946d7a2-1883-4be8-8d9b-52e67047cdbe.png)

**Comment by cthomasONRR** [comment]
I also created a wiki page for when we are ready to add content here: 
https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide

**Comment by jkwonatx** [comment]
I will look more closely into this thread tomorrow. Thank you @cthomasONRR for the work!

**Comment by cthomasONRR** [comment]
@mcharg @jkwonatx I have the following sections updated in the Word document for your review:

- [ ] Adding documents and proper tagging
- [ ] Linking PDFs and other documents

Jae, I had to update your instructions to just focus on linking PDFs in the CMS. I cover how to navigate around the CMS (like getting to pages and content blocks) in other sections. 

Here's the link to the Word doc, I recommend using the Navigation Pane since the doc is long now.
https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@mcharg Thanks! I added these to the wiki, so I will close this issue now
https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide
