### ISSUE TITLE
Complete FOIA page on CMS

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#869]
FOIA:
Page in CMS: https://dev-onrr-cms.app.cloud.gov/admin/collections/pages/31
Page preview: https://dev-onrr-frontend.app.cloud.gov/about-onrr/foia (you may have to go to the homepage and navigate through the menu to not get the 404 page)
Wireframe: https://qmcq5k.axshare.com/#id=7ctmer&p=freedom_of_information_act__foia_
Live page (needed for links that aren't specified in the wireframe): https://www.onrr.gov/foia/index.htm

**Comment by daniel-coleman-1** [comment]
Two issues:
I need the link for "How to Make a Request"
How do I turn the "Submit a Request here" text into a button?

Will bring up tomorrow at stand up

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Nice job, it's looking good.  Here is the link for [how to make a request ](https://www.doi.gov/foia/make-a-request) . Can you also make "Other Information" an  H2, and make the two bullet points under it as links rather than writing out the link (I think @mcharg has it like that in the wireframe as a reminder to what the link is).  And delete the content link to the wireframe. Thanks 
![image](https://user-images.githubusercontent.com/40175688/126492310-e62742ad-75ff-4df6-9487-7390091b68c8.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 

- The NRRD link should go to: https://revenuedata.doi.gov/ (it thinks it's a relative link)
- The Presentations & Testimony link should be a relative link to the Engagement page: /about-onrr/engagement
- The Press Releases link should be a relative link to the Public Affairs page: /about-onrr/public-affairs
- You can remove the How to Make a Request link.  I have no idea where I planned for that to go.
- Maroya is right about the links under Other Information, you can just link the text.
- The Contact email address on the right in the wireframe is missing.  You can just put it at the bottom under an H2, for now, since we don't have the ability to add a second column.


Also, all external links should open in a new tab.

**Comment by daniel-coleman-1** [comment]
@mcharg @Maroyafaied thanks! edits made in page

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.

**Comment by daniel-coleman-1** [comment]
@mcharg I need to find out how to add the button, is that an HTML+CSS function?

**Comment by mcharg** [comment]
@daniel-coleman-1 I don't think that's something in the CMS yet.  Please create an issue to add the ability to add buttons.
