### ISSUE TITLE
Identify glossary terms for onrr.gov 

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#906]
@cthomasONRR  will identify based on top 5 pages visited for users. @codyeckstein will send a list used for onboarding.

**Comment by cthomasONRR** [comment]
@Baymatt  Shannon, Lindsay, and myself discussed, and we think the best way to start is to just add new terms to the existing NRRD glossary. We will eventually put that on the onrr.gov site, and ideally we will have one glossary once NRRD gets put into the CMS.

**Comment by cthomasONRR** [comment]
@Baymatt With the existing onrr.gov glossary, these are the only terms we'd like to keep:
- EMARF
- Federal Register
- FIMO

**Comment by Baymatt** [comment]
Started on the glossary (ONRR_Glossary_Terms.xslx) and uploaded it to teams, can be found in the ONRR.gov folder. Will be continuing to add terms and definitions. Not sure if the terms are too basic/comprehensive, but I figure better safe to include more terms and then we can remove as needed.

**Comment by cthomasONRR** [comment]
@Baymatt Thanks so much for all your work on this! I will also try to add in some terms this week.

**Comment by cthomasONRR** [comment]
Attached is a presentation on glossaries from the Plain Language Writing Summit:
[plain-language-summit-online-glossaries](https://app.zenhub.com/files/210892300/58daf895-93d7-4347-8f67-d180c69a7709/download)

**Comment by cthomasONRR** [comment]
I addition to making a list of terms, here are some things I've been considering based on the Plain Language Summit:

- Other federal agencies put a legal disclaimer on their glossaries. Here's [GSA's for example](https://www.gsa.gov/reference/glossary)
- Here is a version we can use for both onrr and nrrd:
    -  _The definitions in this glossary are simplified. Some are ONRR-specific in their usage. None of the definitions takes precedence over laws, legislation, regulations, contracts, or specific interpretations or rulings._ 
    - This glossary defines many commonly used terms and initialisms but isn’t a full list. To request changes to terms on this list, or to suggest new terms be added, email [ODDD email address].


- The presentation also suggested that you use google analytics to identified your most-used webpages, and make sure you define terms on those popular webpages.
    -  Can we get a list of the top 10 webpages to focus on the terms listed there?

**Comment by mcharg** [comment]
@cthomasONRR Do you want to wait until the end of the month and get the top 10 pages for the fiscal year?

**Comment by cthomasONRR** [comment]
@mcharg Yes, that sounds perfect!

**Comment by cthomasONRR** [comment]
The following locations in ONRR's section of the CFR includes definitions:

[30 CFR 1206.20](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1206#1206.20)
[30 CFR 1204.2](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1204/subpart-A)
[30 CFR 1208.2](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1208/subpart-A)
[30 CFR 1218.51a](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1218)
[30 CFR 1219.411](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1219)
[30 CFR 1220.002](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1220/section-1220.002)
[30 CFR 1241.3b](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1241)
[30 CFR 1243.3](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1243)

1206.20 is our most widely-used and comprehensive list of definitions in the CFR. I don't think we should copy+paste these definitions into onrr.gov because a lot of them are very detailed, specialized, 'in-the-weeds' terms that might confuse rather than help a website user. I think the website definitions should be a bit more general and stay specific to only terms used on the website.

BUT - I wanted to list them here as a resource for terminology and as a basis for how to define some ONRR-specific terms. And of course the onrr.gov definitions will be in plain language (unlike the CFR).

**Comment by cthomasONRR** [comment]
Here is the [Teams link](https://teams.microsoft.com/l/file/E1F922C7-62F9-49FC-80BB-85B80E5EE080?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FONRR_Glossary_Terms.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a) to the Glossary Terms excel. I have about 70 terms identified. I think at this point, I will need to see the top 5 webpages and Cody's onboarding list to add more terms. I think I've exhausted my resources so far!

**Comment by daniel-coleman-1** [comment]
Top five pages for May-September:
![PageviewsMay01-Sep27](https://user-images.githubusercontent.com/83892362/135115832-4a0dbe43-912c-40ea-b428-3f39fb8866b9.png)

and page views for this month so far:
![PageviewsSep1-Sep27](https://user-images.githubusercontent.com/83892362/135115900-fa607908-309e-4bee-b6e5-5a32febe4fe2.png)

**Comment by daniel-coleman-1** [comment]
I can give you other time periods if you'd like, the top 8 seem to generally stay the top 8:
![Top10PagesSept](https://user-images.githubusercontent.com/83892362/135116197-bfa8deb6-98be-473f-9aae-1323475bd9da.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Those pages are for NRRD.  This issue is for onrr.gov.

**Comment by daniel-coleman-1** [comment]
@mcharg whooops, need coffee.  Updating images, thanks for catching.

**Comment by mcharg** [comment]
@daniel-coleman-1 And we were going to wait until the fiscal year is over, so we can pull the pages from the unsampled report that includes a whole fiscal year.

**Comment by mcharg** [comment]
But it probably doesn't hurt to look at pages now, since it likely won't change much.

**Comment by daniel-coleman-1** [comment]
Updated with ONRR pageviews

**Comment by mcharg** [comment]
I think those are pretty consistently the top viewed pages.

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg @daniel-coleman-1 @lpgoldstein 

We have 134 terms listed on our [glossary spreadsheet](https://teams.microsoft.com/l/file/E1F922C7-62F9-49FC-80BB-85B80E5EE080?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FONRR_Glossary_Terms.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a). Could you please review, and comment here if you added any terms and/or if you think any terms should be removed? Thanks!

**Comment by codyeckstein** [comment]
Should we put 2014 in the glossary?

**Comment by cthomasONRR** [comment]
@codyeckstein We are trying not to include forms and acronyms, but I think I'm OK with including 'OGOR' and 'Form ONRR-2014' since these are the 2 most heavily used forms and they appear frequently on the top 10 pages. So let's include those 2 and see if anyone feels strongly about removing them.

**Comment by Maroyafaied** [comment]
@cthomasONRR Are the terms on the spreadsheet are missing terms from the existing glossary on onrr.gov? The existing glossary has form-2014 on there. 
![image](https://user-images.githubusercontent.com/40175688/135520555-7be79ff4-3672-44a3-9acb-724bff810895.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Yes- in the initial meeting the Lindsay and Shannon, we decided not to include forms and acronyms.

**Comment by Maroyafaied** [comment]
@cthomasONRR @codyeckstein I agree with adding OGOR' and 'Form ONRR-2014', they are definitely very heavily used.

**Comment by cthomasONRR** [comment]
@Maroyafaied I think after we develop the glossary, we should have a separate page for "Forms and Acronyms". We could basically move the current glossary to that title since the current glossary only contains forms and acronyms anyway.

**Comment by mcharg** [comment]
I'll review these against the wireframes tomorrow.

**Comment by mcharg** [comment]
I'll also take a look at search terms and see if that identifies any terms.

**Comment by lpgoldstein** [comment]
@cthomasONRR what do you think about adding BOEM since they issue the offshore leases? Also adding "unit" since we have lease, agreement, and communitization agreement?

**Comment by cthomasONRR** [comment]
@lpgoldstein I'm ok with adding those terms... just added them to the spreadsheet.

**Comment by codyeckstein** [comment]
Thoughts on these?

GOMESA
Payor Code
Operator Code
Compensatory Royalty Agreement
Production Allocation Schedule Report (PASR)
Facility Measurement Point (FMP) - A meter for royalty volume determination

**Comment by cthomasONRR** [comment]
@codyeckstein I'm OK adding those terms... please feel free to add them to the spreadsheet

**Comment by codyeckstein** [comment]
will do

**Comment by mcharg** [comment]
Top 20 search terms from FY21.  I should have the top pages on Monday.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/457cdc76-de32-41fd-8ca3-f6297f0111d0)

**Comment by mcharg** [comment]
Here's a list of NRRD terms identified for the query tool.  Might be easier than copying and pasting definitions from the live site. https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Design/Glossaries/glossary.terms.query.tool.xlsx?d=w73985e533c8140a98853a10482f267ab&csf=1&web=1&e=VuAhS7

**Comment by mcharg** [comment]
We should also have a list of definitions for OGOR B disposition codes.  @Maroyafaied Do you know where that doc is?

**Comment by mcharg** [comment]
I added the following that are used in the wireframes. Feel free to remove any that are at too low a level.

- Web Center Portal (ONRR Web Center Portal was in the list, but we don't refer to it as that in the wires.)
- Pay.gov
- BTFA
- P&R Report
- Compliance
- Enforcement
- Data Mining
- Litigation Support
- Revenue
- OCS Qualification Number
- Assignee
- ONRR Operator Number
- ONRR Payor Number
- Solid Minerals Payor Code
- Reporter ID Number
- MRMSS
- User ID
- Disposition
- Inventory
- ASCII
- CSV
- PASR
- Up Front Edits
- Buy-Back
- Metering System
- Flaring
- Venting
- Well Status Code
- Dual Accounting
- Remote Storage Facility
- Unbundling Cost Allocation (UCA)
- Rulemakings
- Electronic Code of Federal Regulations (eCFR)
- Royalty Value Prior to Allowances (RVPA)
- Royalty Value Less Allowances (RVLA)
- Crude Oil Market Center
- Standardized UCA
- Plant-Specific UCA
- FOGRMA
- STRAC
- Indian Outreach
- Tribal Assistance
- Tribal Consultation
- Tribal Lockbox
- FACA
- Standard Operating Procedure (SOP)
- Memorandum of Understanding (MOU)

Note, for all the ones that are acronyms, we should have them spelled out in the actually glossary.

**Comment by cthomasONRR** [comment]
@Maroyafaied We're now up to 191 terms, with 88 of those needing definitions. I would really like to cap this glossary at 200 terms. I plan to make several issues so I can develop definitions in stages instead of all at once, and separate issues to make sure existing definitions are at an appropriate reading level. But I would really like to cap this glossary at 200 terms so this project stays manageable for me. Creating and updating definitions is going to be a very long term project for me.

**Comment by Maroyafaied** [comment]
Here are terms I suggest we add

- Transaction code
- Offshore
- Onshore
- Joint Operating Agreements
- Calendar Month avg
- NYMEX Roll 

And here are terms listed in the excel sheet that I suggest we take out. 

- Area - We have area and designated areas, I think we can get rid of area and keep designated areas
- Check Payment -self explanatory
- Electronic payment - self explanatory 
- Gross Domestic Product - This should be taken out of the NRRD since I don't think we reference to it anymore
- Indian Outreach
- Misconduct
- Tribal Assistance
- Tribal consultation
- Tribal Lockbox - we have lockbox payment already so I don't think the definition will be different for tribal

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks for your input - I just made the updates you suggested in the Excel.

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR here's the OGOR B Disposition codes glossary https://teams.microsoft.com/l/file/ABCBCB23-4E64-48A6-9029-AA3F864277FD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FOGOR%20B%2FOGOR.B.Disposition.Categories.Glossary-2.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a
