### ISSUE TITLE
Component: Math

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#944]
Can we have the ability to put in text like this?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/40d1fb93-b402-4ac1-bb4d-ac622b433317)

**Comment by mcharg** [comment]
@jpetersononrr Are there any more complicated examples that it would be good for our developers to look at when researching whether we can add math text?

**Comment by jpetersononrr** [comment]
I can share the draft copies of our stuff with you.  It’s going to be the same concept as the ones that already exist in terms of equations.  They don’t get more complicated than what’s already in the processed example.  If you’d like to share a word version with them or anything, let me know and I’ll send you a file!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.***
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: mcharg ***@***.***>
Sent: Thursday, August 19, 2021 2:38 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Component: Math (#944)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C95b29127d747474d02ef08d963513e38%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650022860589100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qY4gZECzAYuZ3y7CoI6AqTLOizaieS0arZoWq5UrHDo%3D&reserved=0> Are there any more complicated examples that it would be good for our developers to look at when researching whether we can add math text?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F944%23issuecomment-902228212&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C95b29127d747474d02ef08d963513e38%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650022860589100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kZXXi6PrkBMujt0Ex7uzdUrkW4C8yFf3zRA8vDH6bGE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPLRT7PMPVJ2AE4DX4C37W3T5VTRTANCNFSM5CO7FOKA&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C95b29127d747474d02ef08d963513e38%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650022860599053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ru1I1KrlslkyrXPUSFFXoFjIRAhMdqIeUv8pYIJ%2ByTI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C95b29127d747474d02ef08d963513e38%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650022860599053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FysuVAQpaql24yCr0g5ZrasNZHPwRSDRTHeTqliR1yE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C95b29127d747474d02ef08d963513e38%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650022860609009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ddEvDri4MKTDJevvt%2BNdcf6hwkEsQWu4KjklWKhaN%2Fw%3D&reserved=0>.

**Comment by mcharg** [comment]
@jpetersononrr, @mojobnichols found this that will allow editing math equations: https://www.npmjs.com/package/editorjs-math

**Comment by mcharg** [comment]
@jpetersononrr here's another option. http://www.mathjax.org/

**Comment by jpetersononrr** [comment]
This second one looks pretty easy to pick up. A few of the html items I tried didn’t work (we use subscript on some of our math) but that doesn’t mean someone couldn’t help me do it correctly.  That would be nice!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.***
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: mcharg ***@***.***>
Sent: Friday, August 20, 2021 6:10 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Component: Math (#944)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283608624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xTSweHlHPdD6uNlCIjhKfZmL2hu7kpJnpNlOnz3vC6A%3D&reserved=0> here's another option. http://www.mathjax.org/<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.mathjax.org%2F&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283618581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dGSdEPUk%2F1hwQuTclq0hc3G6LOsEvEjZ2GIsBJvkGOA%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F944%23issuecomment-902646728&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283618581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eHz00KahLjYU%2BCaNRfdkJmAqjgoTMhTXB8RbNjVWxpM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPLRT7NOJTP2MKO65PHW32DT5ZA2LANCNFSM5CO7FOKA&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283628525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EE8Cq%2BUAjYliKYRtLrXOT5v5%2FWaYdwjzVO%2FTeQkwOkQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283628525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7bbAC2n4W98XW7RD0GIMnJ8QmbayHmX%2B2EzJezvQt%2FQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjodie.peterson%40onrr.gov%7Cf5dfd9c5d8e1434c5be708d963d37ec3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637650582283638481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R6qy5r5PfXgfpC6C6iA4qzOxTARnf6YQxB7rPgF3ocs%3D&reserved=0>.

**Comment by mcharg** [comment]
RV will continue providing the equations as images with alt text.
