### ISSUE TITLE
Make new reporter checklists work for user testing

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#954]

**Comment by mcharg** [comment]
The checklists all now work.  @cthomasONRR or @lpgoldstein Does one of you want to review to make sure I didn't hook anything up wrong?
https://qmcq5k.axshare.com/#id=muwj32&p=new_reporter_setup

**Comment by cthomasONRR** [comment]
@mcharg Sure! I'll go in and see if I can break anything ;)

**Comment by cthomasONRR** [comment]
@mcharg 

Questions:
- For Forms ONRR-4444 and W-9, is the only option for new reporters to physically mail them in? No email or fax options? Maybe RRM will provide us better information/want to update this when they review.
- This is likely just the wireframe setup, but if I want to switch between options for 'What are you reporting?' I have to refresh the page for it to work.
-  For Solid Minerals, instead of having specific people listed as a point of contact for 'Get an ONRR payor number', there is a link to a PDF. Is it possible that we can extract the contact information and display it like the other 'What are you reporting?' options? This is also likely something RRM needs to do.

Other than that, this is so much easier to read and understand compared to what is currently on the website!!! It looks very clean, logical, and easy to process! Thanks so much for all your work on this.

**Comment by mcharg** [comment]
@cthomasONRR 
* I'm pretty sure they have to mail the 4444 and W-9.
* That is the wireframe setup.  It would be a lot more work to make it changeable without refreshing.
* I just swapped out the pdf with a link to the solids contacts page.  That team really likes sending people to the contacts list.  Maybe they'll change their mind once we show them how easy it is to update contact info in the CMS.
