### ISSUE TITLE
Find links for Crude Oil Market Centers publications

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#995]
We have them listed with no links.
https://www.onrr.gov/valuation/Crude-Oil-Market-Centers.htm

**Comment by cthomasONRR** [comment]
We should have someone from MSA review/approve this too.

- [ ] Argus American Crude: https://www.argusmedia.com/en/crude-oil/argus-americas-crude
- [ ] Platts Oilgram Price Report: https://www.spglobal.com/platts/en/products-services/oil/oilgram-price-report

**Comment by cthomasONRR** [comment]
@Baymatt I'm having trouble finding a direct link to the following:
- [ ] Platts Price Average Supplement

Can you see if you can find a direct link like the ones I have above? I'm suspicious that this is for supplement prices within the Platts Oilgram Price Report, but I might be wrong.

Once you research, we will send an email to a MSA contact for them to verify.

Thanks!

**Comment by Baymatt** [comment]
@cthomasONRR The closest document I've found is https://www.spglobal.com/platts/PlattsContent/_assets/_files/en/our-methodology/methodology-specifications/market-parity-price-faq.pdf within the Crude Oil Methodology Supporting Materials found here, https://www.spglobal.com/platts/en/our-methodology/methodology-specifications/oil/crude-oil-methodology 

Let me know if this isn't what we're looking for and I can do some more digging.

**Comment by cthomasONRR** [comment]
@Baymatt Thanks! Tomorrow I will draft an email to Damion Schulte and see if he can verify that we found the correct links.

**Comment by cthomasONRR** [comment]
I sent the following email to Damion:

"Hi Damion,

We are working on updating the onrr.gov website, and I noticed that the Crude Oil Market Centers webpage (https://www.onrr.gov/valuation/Crude-Oil-Market-Centers.htm) does not have links for the approved publications. 

I went online and tried to find appropriate links. Could you review and approve the links I found? Or, if you do not want the links, please let me know and I won’t update the webpage.

•	Argus American Crude: https://www.argusmedia.com/en/crude-oil/argus-americas-crude
•	Platts Oilgram Price Report: https://www.spglobal.com/platts/en/products-services/oil/oilgram-price-report
•	Platts Price Average Supplement: https://www.spglobal.com/platts/PlattsContent/_assets/_files/en/our-methodology/methodology-specifications/market-parity-price-faq.pdf 

We were uncertain if the Platts Price Average Supplement is its own publication, or if it is a price within the Oilgram Price Report.

Thanks so much for your time and help!

Christine Thomas"

**Comment by cthomasONRR** [comment]
Damion responded and included Robert Sudar for his input: 

"Hey Christine,  So for the approved publication a company has to have a subscription to them in order to get into them.  My guess would be that anyone looking for the market centers would already have these subscriptions.  I’m not sure if putting the links in there is a good idea or not.  Thanks is why I included Robert on this.  That being said the Price Average Supplement would be part of the Oilgram.  I’ll let Robert respond with his thoughts.  Thanks "

**Comment by cthomasONRR** [comment]
Response from Robert Sudar: 

"We added the links to the Federal Gas Index page. For consistency, I see why we'd add the links here. However, I think oil market centers are only used in non-arm's length valuation situations and most of those situations are companies that already have a subscription to one of these so a link might not be worth it.

Damion's right, the price supplement is part of the subscription to the Oilgram price report. You could get the prices necessary from either document, so if a company could subscribe to only the once a month, Price Average Supplement rather than the daily Oilgram Price Report, they would be able to report royalties without issue and maybe save money. There's no clear right way for the website to be. I'm fine with however you'd like to proceed as the content overseer of the page."

**Comment by cthomasONRR** [comment]
I will add the following links:

•	Argus American Crude: https://www.argusmedia.com/en/crude-oil/argus-americas-crude
•	Platts Oilgram Price Report: https://www.spglobal.com/platts/en/products-services/oil/oilgram-price-report
•	Platts Price Average Supplement: https://www.spglobal.com/platts/en/products-services/oil/oilgram-price-report

**Comment by cthomasONRR** [comment]
@mcharg 
Can you review the dev site to make sure I added in the links correctly? They look ok to me but want an extra set of eyes before moving it to the live site.
http://2017onrr/valuation/Crude-Oil-Market-Centers.htm

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
Links are now live. Closing issue.
